name: CI/CD
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
      name: Deploy Production
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: yarn && yarn run build
        - name: Publish
          uses: cloudflare/pages-action@1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: 'vite-batatabit'
            directory: 'dist'
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
